### ISSUE TITLE
An XMM + eROSITA sample is assigning an XMM image to the wrong source (it doesn't have that ObsID)

### ISSUE THREAD

**Issue by DavidT3** [DavidT3/XGA#1135]
Jess discovered this, while doing XMM + eROSITA analysis of the sample from Kostas paper. More details will follow.

**Comment by jessicapilling** [comment]
I'm going to keep track of debugging here:

What is ruled out:
1. The product is being assigned with the correct obsid. I.e. product.obs_id matches the obsid in the header of the product
2. The sources are know the correct obs_ids that they are associated with

Where something is going wrong:
1. I first put print statements right before the error is raised in update_products and the wrong source/ product pair is being input into this function. ie. somewhere in the code, there is a src.update_products(<incorrect product object>)
2. we suspect this to occur in run.py, in sas call and esass call, indeed these call update_products

The next comment will be about investigating run.py

**Comment by jessicapilling** [comment]
Within sas_call I have:
1. printed 'sources' which is the first argument sent to the sas_func, in this case it is a xga.samples.extended.ClusterSample object 
2. then I printed the length of the sample - which was 14, the length of the df I declared the ClusterSample is 15, so maybe there is a source that didn't match to any data?  It says that 15/15 BaseSource Sample was declared.
3. I printed sources.src_obs_ids , this only had 14 clusters, but the ob_ids were assigned correctly
4. I printed cmd_list, and its length, and this was 13!!!

So there is a mismatch in the length of cmd_list and the length of the sample being input into the cmd.

So when the code does:
for ind in range(len(cmd_list)):
- source = sources[ind]
This is actually wrong, because there is one less entry in cmd_list than in source

Then this is where the problem originates within sas_call.

So the next step is going to where the sas_func is called, and see why sources and cmd_list (and p_type, path, and extra_info - these are all length 13) are different lengths

**Comment by jessicapilling** [comment]
Ok, so within eexpmap line 75:
- if 'xmm' not in source.telescopes:
--continue

So no cmd is added to the list, and then they are different lengths, and this is what causes the bug in run.py

Also explains why the error doesnt happen when you specify one telescope in a sample.

Now I can start fixing the bug!

**Comment by jessicapilling** [comment]
Ok so one solution is in all of the product generation functions, we need to go from:

        if 'xmm' not in source.telescopes:
            continue

        cmds = []
        final_paths = []
        extra_info = []

To something like this:

        cmds = []
        final_paths = []
        extra_info = []

        if 'xmm' not in source.telescopes:
            sources_cmds.append(np.array(cmds))
            sources_paths.append(np.array(final_paths))
            sources_extras.append(np.array(extra_info))

**Comment by jessicapilling** [comment]
Alternatively, it might be nicer to deal with this in sas_call and esass_call. I think this would involve more editing overall because we would have to deal with 'sources' being one length and cmd_list, p_type, paths, extra_info being another length. But we could do something along the lines of:

Instead of:
        for ind in range(len(cmd_list)):
            source = sources[ind]
            if len(cmd_list[ind]) > 0:
                src_lookup[repr(source)] = ind

We could do:
         xmm_sources = [src for src in sources if 'xmm' in src.telescopes]
         for ind in range(len(cmd_list)):
            source = xmm_sources[ind]
            if len(cmd_list[ind]) > 0:
                src_lookup[repr(source)] = ind
Then wherever we do sources[ind], we replace it with xmm_sources[ind]

And do a similar thing for dealing with the paths, p_type, and extra_info variables, although I havent looked at how those are affected yet.

**Comment by jessicapilling** [comment]
@DavidT3  I have found the cause of the bug and come up with two ways to fix it (see the two previous comments). Which one do you think is best/ shall we discuss before I implement one of them?

**Comment by DavidT3** [comment]
@jessicapilling let's go with your first solution initially, but we should consider better ways of passing out the generate commands in future - maybe passing them out as dictionaries with source representations as keys? 

But let's just get it working again first

**Comment by DavidT3** [comment]
@jessicapilling - if you're satisfied this is resolved, you can have the satisfaction of closing the issue!
